### ISSUE TITLE
Error when trying to run the OBJ example

### ISSUE THREAD

**Issue by Trintusly** [mario-deluna/php-render#2]
PHP Parse error:  syntax error, unexpected 'Mat4' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

**Comment by mario-deluna** [comment]
Hi there, you are probably running a PHP version before 7.4 which does not allow typed class properties.

**Comment by Trintusly** [comment]
Yea, rookie mistake. Thanks.
