### ISSUE TITLE
How can generate image for WEB online?

### ISSUE THREAD

**Issue by poleg-on** [mario-deluna/php-render#4]
If I understood correctly, then the examples should be executed in CMD.

How can i do?

$im = ... php-render
header('Content-Type: image/png');
imagepng($im);

**Comment by mario-deluna** [comment]
The TGA Renderer at https://github.com/mario-deluna/php-render/blob/master/src/Render/TGARenderer.php#L19 returns a `.tga` image. So, technically, you can just do the following:

```php
$im = $tgarenderer->render($context);
header('Content-Type: image/tga');
echo $im;
```

However, I'm not sure if browsers support the `tga` format natively. If they don't, you might need to convert it to PNG or JPG first.

If you use [php-glfw](https://github.com/mario-deluna/php-glfw), you can utilize a Buffer Object to directly write a JPG or PNG from a bitmap.

Alternatively, you can use php-glfw directly if you want reasonable performance. You can even use it in headless mode (i.e., for the web) as described [here](https://phpgl.net/user-guide/offscreen/render-to-image.html).

**Comment by poleg-on** [comment]
Thank you! I will try
